import { Grade, Topic, Lesson, ResourceType, Resource } from './types';

export const GRADES: Grade[] = [
  { id: 'g10', name: 'Tin học 10' },
  { id: 'g11', name: 'Tin học 11' },
  { id: 'g12', name: 'Tin học 12' },
];

export const TOPICS: Topic[] = [
  // Lớp 10
  { id: 't10_1', grade_id: 'g10', name: 'Chủ đề 1: Máy tính và xã hội tri thức' },
  { id: 't10_2', grade_id: 'g10', name: 'Chủ đề 2: Mạng máy tính và Internet' },
  { id: 't10_3', grade_id: 'g10', name: 'Chủ đề 3: Đạo đức, pháp luật và văn hóa trong môi trường số' },
  { id: 't10_4', grade_id: 'g10', name: 'Chủ đề 4: Ứng dụng Tin học' },
  { id: 't10_5', grade_id: 'g10', name: 'Chủ đề 5: Giải quyết vấn đề với sự trợ giúp của máy tính' },
  { id: 't10_6', grade_id: 'g10', name: 'Chủ đề 6: Hướng nghiệp với Tin học' },
  
  // Lớp 11
  { id: 't11_1', grade_id: 'g11', name: 'Chủ đề 1: Máy tính và xã hội tri thức' },
  { id: 't11_2', grade_id: 'g11', name: 'Chủ đề 2: Tổ chức lưu trữ, tìm kiếm và trao đổi thông tin' },
  { id: 't11_3', grade_id: 'g11', name: 'Chủ đề 3: Đạo đức, pháp luật và văn hóa trong môi trường số' },
  { id: 't11_4', grade_id: 'g11', name: 'Chủ đề 4: Giới thiệu các hệ cơ sở dữ liệu' },
  { id: 't11_5', grade_id: 'g11', name: 'Chủ đề 5: Hướng nghiệp với Tin học' },
  { id: 't11_6', grade_id: 'g11', name: 'Chủ đề 6: Thực hành tạo và khai thác cơ sở dữ liệu' },
  { id: 't11_7', grade_id: 'g11', name: 'Chủ đề 7: Phần mềm chỉnh sửa ảnh và làm Video' },

  // Lớp 12
  { id: 't12_1', grade_id: 'g12', name: 'Chủ đề 1: Máy tính và xã hội tri thức' },
  { id: 't12_2', grade_id: 'g12', name: 'Chủ đề 2: Mạng máy tính và Internet' },
  { id: 't12_3', grade_id: 'g12', name: 'Chủ đề 3: Đạo đức, pháp luật và văn hóa trong môi trường số' },
  { id: 't12_4', grade_id: 'g12', name: 'Chủ đề 4: Giải quyết vấn đề với sự trợ giúp của máy tính' },
  { id: 't12_5', grade_id: 'g12', name: 'Chủ đề 5: Hướng nghiệp với Tin học' },
  { id: 't12_6', grade_id: 'g12', name: 'Chủ đề 6: Máy tính và xã hội tri thức' },
  { id: 't12_7', grade_id: 'g12', name: 'Chủ đề 7: Ứng dụng Tin học' },
];

export const LESSONS: Lesson[] = [
  // Lớp 10
  { id: 'l10_1_1', topic_id: 't10_1', name: 'Bài 1: Thông tin và xử lí thông tin' },
  { id: 'l10_1_2', topic_id: 't10_1', name: 'Bài 2: Vai trò của thiết bị thông minh và tin học đối với xã hội' },
  { id: 'l10_1_7', topic_id: 't10_1', name: 'Bài 7. Thực hành sử dụng thiết bị số thông dụng' },
  { id: 'l10_2_8', topic_id: 't10_2', name: 'Bài 8: Mạng máy tính trong cuộc sống hiện đại' },
  { id: 'l10_2_9', topic_id: 't10_2', name: 'Bài 9: An toàn trên không gian mạng' },
  { id: 'l10_2_10', topic_id: 't10_2', name: 'Bài 10. Thực hành khai thác tài nguyên trên Internet' },
  { id: 'l10_3_11', topic_id: 't10_3', name: 'Bài 11. Ứng xử trên môi trường số. Nghĩa vụ tôn trọng bản quyền' },
  { id: 'l10_4_12', topic_id: 't10_4', name: 'Bài 12. Phần mềm thiết kế đồ họa' },
  { id: 'l10_4_13', topic_id: 't10_4', name: 'Bài 13. Bổ sung các đối tượng đồ họa' },
  { id: 'l10_4_14', topic_id: 't10_4', name: 'Bài 14. Làm việc với đối tượng đường và văn bản' },
  { id: 'l10_4_15', topic_id: 't10_4', name: 'Bài 15. Hoàn thiện hình ảnh đồ họa' },
  { id: 'l10_5_16', topic_id: 't10_5', name: 'Bài 16. Ngôn ngữ lập trình bậc cao Python' },
  { id: 'l10_5_17', topic_id: 't10_5', name: 'Bài 17. Biến và lệnh gán' },
  { id: 'l10_5_18', topic_id: 't10_5', name: 'Bài 18. Các lệnh vào ra đơn giản' },
  { id: 'l10_5_19', topic_id: 't10_5', name: 'Bài 19. Câu lệnh rẽ nhánh if' },
  { id: 'l10_5_20', topic_id: 't10_5', name: 'Bài 20. Câu lệnh lặp for' },
  { id: 'l10_5_21', topic_id: 't10_5', name: 'Bài 21. Câu lệnh lặp while' },
  { id: 'l10_5_22', topic_id: 't10_5', name: 'Bài 22. Kiểu dữ liệu danh sách' },
  { id: 'l10_5_23', topic_id: 't10_5', name: 'Bài 23. Một số lệnh làm việc với dữ liệu danh sách' },
  { id: 'l10_5_24', topic_id: 't10_5', name: 'Bài 24. Xâu kí tự' },
  { id: 'l10_5_25', topic_id: 't10_5', name: 'Bài 25. Một số lệnh làm việc với xâu kí tự' },
  { id: 'l10_5_26', topic_id: 't10_5', name: 'Bài 26. Hàm trong Python' },
  { id: 'l10_5_27', topic_id: 't10_5', name: 'Bài 27. Tham số của hàm' },
  { id: 'l10_5_28', topic_id: 't10_5', name: 'Bài 28. Phạm vi của biến' },
  { id: 'l10_5_29', topic_id: 't10_5', name: 'Bài 29. Nhận biết lỗi chương trình' },
  { id: 'l10_5_30', topic_id: 't10_5', name: 'Bài 30. Kiểm thử và gỡ lỗi chương trình' },
  { id: 'l10_5_31', topic_id: 't10_5', name: 'Bài 31. Thực hành viết chương trình đơn giản' },
  { id: 'l10_5_32', topic_id: 't10_5', name: 'Bài 32. Ôn tập lập trình Python' },
  { id: 'l10_6_33', topic_id: 't10_6', name: 'Bài 33. Nghề thiết kế đồ họa máy tính' },
  { id: 'l10_6_34', topic_id: 't10_6', name: 'Bài 34. Nghề phát triển phần mềm' },

  // Lớp 11
  { id: 'l11_1_1', topic_id: 't11_1', name: 'Bài 1. Hệ điều hành' },
  { id: 'l11_1_2', topic_id: 't11_1', name: 'Bài 2. Thực hành sử dụng hệ điều hành Khám phá thế giới thiết bị số thông minh' },
  { id: 'l11_1_3', topic_id: 't11_1', name: 'Bài 3. Phần mềm nguồn mở và phần mềm chạy trên Internet' },
  { id: 'l11_1_4', topic_id: 't11_1', name: 'Bài 4. Bên trong máy tính' },
  { id: 'l11_1_5', topic_id: 't11_1', name: 'Bài 5. Kết nối máy tính với các thiết bị số' },
  { id: 'l11_2_6', topic_id: 't11_2', name: 'Bài 6. Lưu trữ và chia sẻ tệp tin trên Internet' },
  { id: 'l11_2_7', topic_id: 't11_2', name: 'Bài 7. Thực hành tìm kiếm thông tin trên Internet' },
  { id: 'l11_2_8', topic_id: 't11_2', name: 'Bài 8. Thực hành nâng cao sử dụng thư điện tử và mạng xã hội' },
  { id: 'l11_3_9', topic_id: 't11_3', name: 'Bài 9. Giao tiếp an toàn trên Internet' },
  { id: 'l11_4_10', topic_id: 't11_4', name: 'Bài 10. Lưu trữ dữ liệu và khai thác thông tin phục vụ quản lí' },
  { id: 'l11_4_11', topic_id: 't11_4', name: 'Bài 11. Cơ sở dữ liệu' },
  { id: 'l11_4_12', topic_id: 't11_4', name: 'Bài 12. Hệ quản trị cơ sở dữ liệu và hệ cơ sở dữ liệu.' },
  { id: 'l11_4_13', topic_id: 't11_4', name: 'Bài 13. Cơ sở dữ liệu quan hệ' },
  { id: 'l11_4_14', topic_id: 't11_4', name: 'Bài 14. SQL - Ngôn ngữ truy vấn có cấu trúc' },
  { id: 'l11_4_15', topic_id: 't11_4', name: 'Bài 15. Bảo mật và an toàn hệ cơ sở dữ liệu' },
  { id: 'l11_5_16', topic_id: 't11_5', name: 'Bài 16. Nghề quản trị cơ sở dữ liệu' },
  { id: 'l11_6_17', topic_id: 't11_6', name: 'Bài 17. Quản trị cơ sở dữ liệu trên máy tính' },
  { id: 'l11_6_18', topic_id: 't11_6', name: 'Bài 18. Thực hành xác định cấu trúc bảng và các trường khóa' },
  { id: 'l11_6_19', topic_id: 't11_6', name: 'Bài 19. Thực hành tạo lập cơ sở dữ liệu và các bảng' },
  { id: 'l11_6_20', topic_id: 't11_6', name: 'Bài 20. Thực hành tạo lập các bảng có khóa ngoài' },
  { id: 'l11_6_21', topic_id: 't11_6', name: 'Bài 21. Thực hành cập nhật và truy xuất dữ liệu các bảng' },
  { id: 'l11_6_22', topic_id: 't11_6', name: 'Bài 22. Thực hành cập nhật bảng dữ liệu có tham chiếu' },
  { id: 'l11_6_23', topic_id: 't11_6', name: 'Bài 23. Thực hành truy xuất dữ liệu qua liên kết các bảng' },
  { id: 'l11_6_24', topic_id: 't11_6', name: 'Bài 24. Thực hành sao lưu dữ liệu' },
  { id: 'l11_7_25', topic_id: 't11_7', name: 'Bài 25. Phần mềm chỉnh sửa ảnh' },
  { id: 'l11_7_26', topic_id: 't11_7', name: 'Bài 26. Công cụ tinh chỉnh màu sắc và công cụ chọn' },
  { id: 'l11_7_27', topic_id: 't11_7', name: 'Bài 27. Công cụ vẽ và một số ứng dụng' },
  { id: 'l11_7_28', topic_id: 't11_7', name: 'Bài 28. Tạo ảnh động' },
  { id: 'l11_7_29', topic_id: 't11_7', name: 'Bài 29. Khám phá phần mềm làm phim' },
  { id: 'l11_7_30', topic_id: 't11_7', name: 'Bài 30. Biên tập phim' },
  { id: 'l11_7_31', topic_id: 't11_7', name: 'Bài 31. Thực hành tạo phim hoạt hình' },

  // Lớp 12
  { id: 'l12_1_1', topic_id: 't12_1', name: 'Bài 1: Làm quen với Trí tuệ nhân tạo' },
  { id: 'l12_1_2', topic_id: 't12_1', name: 'Bài 2. Trí tuệ nhân tạo trong khoa học và đời sống' },
  { id: 'l12_2_3', topic_id: 't12_2', name: 'Bài 3. Một số thiết bị mạng thông dụng' },
  { id: 'l12_2_4', topic_id: 't12_2', name: 'Bài 4. Giao thức mạng' },
  { id: 'l12_2_5', topic_id: 't12_2', name: 'Bài 5. Thực hành chia sẻ tài nguyên trên mạng' },
  { id: 'l12_6_22', topic_id: 't12_6', name: 'Bài 22. Thực hành kết nối các thiết bị số' },
  { id: 'l12_3_6', topic_id: 't12_3', name: 'Bài 6. Giao tiếp và ứng xử trong không gian mạng' },
  { id: 'l12_4_7', topic_id: 't12_4', name: 'Bài 7. HTML và cấu trúc trang web' },
  { id: 'l12_4_8', topic_id: 't12_4', name: 'Bài 8. Định dạng văn bản' },
  { id: 'l12_4_9', topic_id: 't12_4', name: 'Bài 9. Tạo danh sách, bảng' },
  { id: 'l12_4_10', topic_id: 't12_4', name: 'Bài 10. Tạo liên kết' },
  { id: 'l12_4_11', topic_id: 't12_4', name: 'Bài 11. Chèn tệp tin đa phương tiện và khung nội tuyến vào trang web' },
  { id: 'l12_4_12', topic_id: 't12_4', name: 'Bài 12. Tạo biểu mẫu' },
  { id: 'l12_4_13', topic_id: 't12_4', name: 'Bài 13. Khái niệm, vai trò của CSS' },
  { id: 'l12_4_14', topic_id: 't12_4', name: 'Bài 14. Định dạng văn bản bằng CSS' },
  { id: 'l12_4_15', topic_id: 't12_4', name: 'Bài 15. Tạo màu cho chữ và nền' },
  { id: 'l12_4_16', topic_id: 't12_4', name: 'Bài 16. Định dạng khung' },
  { id: 'l12_4_17', topic_id: 't12_4', name: 'Bài 17. Các mức ưu tiên của bộ chọn' },
  { id: 'l12_4_18', topic_id: 't12_4', name: 'Bài 18. Thực hành tổng hợp thiết kế trang web' },
  { id: 'l12_5_19', topic_id: 't12_5', name: 'Bài 19. Dịch vụ sửa chữa và bảo trì máy tính' },
  { id: 'l12_5_20', topic_id: 't12_5', name: 'Bài 20. Nhóm nghề quản trị trong ngành Công nghệ thông tin' },
  { id: 'l12_5_21', topic_id: 't12_5', name: 'Bài 21. Hội thảo hướng nghiệp' },
  { id: 'l12_7_23', topic_id: 't12_7', name: 'Bài 23. Chuẩn bị xây dựng trang web' },
  { id: 'l12_7_24', topic_id: 't12_7', name: 'Bài 24. Xây dựng phần đầu trang web' },
  { id: 'l12_7_25', topic_id: 't12_7', name: 'Bài 25. Xây dựng phần thân và chân trang web' },
  { id: 'l12_7_26', topic_id: 't12_7', name: 'Bài 26. Liên kết và thanh điều hướng' },
  { id: 'l12_7_27', topic_id: 't12_7', name: 'Bài 27. Biểu mẫu trên trang web' },
  { id: 'l12_7_28', topic_id: 't12_7', name: 'Bài 28. Thực hành tổng hợp' },
];

export const RESOURCE_TYPES: ResourceType[] = [
  { id: 'rt_ppt', name: 'Bài giảng PowerPoint', iconName: 'MonitorPlay', color: 'text-orange-600 dark:text-orange-400', bg: 'bg-orange-50 dark:bg-orange-950/35 border-orange-100 dark:border-orange-900/50' },
  { id: 'rt_doc', name: 'Phiếu học tập', iconName: 'FileText', color: 'text-blue-600 dark:text-blue-400', bg: 'bg-blue-50 dark:bg-blue-950/35 border-blue-100 dark:border-blue-900/50' },
  { id: 'rt_test', name: 'Đề kiểm tra', iconName: 'CheckCircle', color: 'text-rose-600 dark:text-rose-400', bg: 'bg-rose-50 dark:bg-rose-950/35 border-rose-100 dark:border-rose-900/50' },
  { id: 'rt_vid', name: 'Video hướng dẫn', iconName: 'Video', color: 'text-purple-600 dark:text-purple-400', bg: 'bg-purple-50 dark:bg-purple-950/35 border-purple-100 dark:border-purple-900/50' },
  { id: 'rt_img', name: 'Hình ảnh minh họa', iconName: 'Image', color: 'text-emerald-600 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-950/35 border-emerald-100 dark:border-emerald-900/50' },
  { id: 'rt_prac', name: 'File thực hành', iconName: 'Code', color: 'text-indigo-600 dark:text-indigo-400', bg: 'bg-indigo-50 dark:bg-indigo-950/35 border-indigo-100 dark:border-indigo-900/50' },
  { id: 'rt_mind', name: 'Sơ đồ tư duy', iconName: 'GitBranch', color: 'text-teal-600 dark:text-teal-400', bg: 'bg-teal-50 dark:bg-teal-950/35 border-teal-100 dark:border-teal-900/50' },
];

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res1',
    title: 'Tin học 10 – Thông tin và xử lí thông tin',
    description: 'Bài giảng chi tiết có hiệu ứng sinh động, thiết kế trực quan giúp học sinh tiếp thu đầy đủ khái niệm về thông tin, dữ liệu, vật mang tin và các bước cơ bản trong quá trình xử lý thông tin.',
    grade_id: 'g10',
    topic_id: 't10_1',
    lesson_id: 'l10_1_1',
    resource_type_id: 'rt_ppt',
    file_name: 'Bai1_TinHoc10_ThongTinSuLy.pptx',
    file_size: '5.2 MB',
    uploaded_by: 'GV. Nguyễn Văn A',
    view_count: 152,
    download_count: 45,
    created_at: '2026-03-05T08:00:00Z'
  },
  {
    id: 'res2',
    title: 'Phiếu học tập – An toàn trên không gian mạng',
    description: 'Phiếu bài tập nhóm dành cho 4 học sinh thảo luận về các nguy cơ mất an toàn trên mạng, các hành vi ứng xử đúng đắn, và cách phòng tránh lừa đảo, mã độc trên môi trường số.',
    grade_id: 'g10',
    topic_id: 't10_2',
    lesson_id: 'l10_2_9',
    resource_type_id: 'rt_doc',
    file_name: 'PHT_AnToanMang_CauHoiNhom.docx',
    file_size: '1.1 MB',
    uploaded_by: 'GV. Trần Thị B',
    view_count: 89,
    download_count: 30,
    created_at: '2026-04-12T08:00:00Z'
  },
  {
    id: 'res3',
    title: 'Đề kiểm tra giữa kỳ I – Tin học 10 (Kèm Ma Trận & Đáp Án)',
    description: 'Bộ đề kiểm tra trắc nghiệm 100% gồm 40 câu hỏi bảo quát từ Chủ đề 1 đến hết Chủ đề 3. Có kèm file ma trận nhận thức, bảng đặc tả và file đáp án chi tiết dành cho giáo viên chấm thi.',
    grade_id: 'g10',
    topic_id: null,
    lesson_id: null,
    resource_type_id: 'rt_test',
    file_name: 'DeKT_GiuaKi1_TH10_FullGiai.pdf',
    file_size: '2.5 MB',
    uploaded_by: 'Admin',
    view_count: 320,
    download_count: 150,
    created_at: '2026-05-15T08:00:00Z'
  },
  {
    id: 'res4',
    title: 'Video hướng dẫn nội quy phòng máy thực hành',
    description: 'Video ngắn giới thiệu các quy tắc an toàn điện, cách bảo quản thiết bị số, nội quy đi dép, xắp xếp chỗ ngồi và quy trình tắt/máy đúng kỹ thuật cho học sinh khối 10 khi bắt đầu năm học mới.',
    grade_id: 'g10',
    topic_id: null,
    lesson_id: null,
    resource_type_id: 'rt_vid',
    file_name: 'NoiQuyPhongMay_THPT_Chuan.mp4',
    file_size: '120.0 MB',
    uploaded_by: 'Admin',
    view_count: 500,
    download_count: 80,
    created_at: '2026-02-25T08:00:00Z'
  },
  {
    id: 'res5',
    title: 'File thực hành HTML cơ bản – Tạo Trang Web Cá Nhân',
    description: 'Source mẫu chứa file index.html và style.css cơ bản của Bài 7 & Bài 8 Tin học 12. Học sinh có thể tải về chạy trực tiếp để xem cấu trúc và chỉnh sửa thông tin cá nhân làm bài tập.',
    grade_id: 'g12',
    topic_id: 't12_4',
    lesson_id: 'l12_4_7',
    resource_type_id: 'rt_prac',
    file_name: 'ThucHanh_WebCaNhan_HTML_CSS.zip',
    file_size: '4.8 MB',
    uploaded_by: 'GV. Lê Văn C',
    view_count: 65,
    download_count: 20,
    created_at: '2026-05-10T08:00:00Z'
  },
  {
    id: 'res6',
    title: 'Sơ đồ tư duy (Mindmap) – Hệ Cơ Sở Dữ Liệu Quan Hệ',
    description: 'Sơ đồ tư duy dạng ảnh phân giải cao tóm tắt toàn bộ khái niệm mô hình dữ liệu quan hệ, các ràng buộc toàn vẹn, khóa chính, khóa ngoài và các thao tác cập nhật dữ liệu cốt lõi môn Tin học 11.',
    grade_id: 'g11',
    topic_id: 't11_4',
    lesson_id: 'l11_4_13',
    resource_type_id: 'rt_mind',
    file_name: 'Mindmap_CsdlQuanHe_FullHD.png',
    file_size: '3.2 MB',
    uploaded_by: 'GV. Nguyễn Văn A',
    view_count: 110,
    download_count: 42,
    created_at: '2026-04-05T08:00:00Z'
  }
];
